### ISSUE TITLE
Histogram/Summary: Currently not possible to .observe(0)

### ISSUE THREAD

**Issue by shatting** [siimon/prom-client#20]
if not used with a prior .labels() call.

see https://github.com/siimon/prom-client/blob/master/lib/histogram.js#L65, 0 gets `||`ed to {},

```
histogram = new require("node-prom").Histogram(..);
histogram.observe(0);
```
results in 
```
Error: Value is not a valid number
  at ../node_modules/prom-client/lib/summary.js:210:10
  at Summary.observe (../node_modules/prom-client/lib/summary.js:57:34)
```

**Comment by siimon** [comment]
Thanks for reporting the issue, should be fixed in 3.4.5
