### ISSUE TITLE
collect cluster metrics could crash the application

### ISSUE THREAD

**Issue by lynhnn** [siimon/prom-client#249]
The master process may crash while collecting cluster metrics on a dead worker. Below is the crash exception when "process.send" to a dead end.

events.js:173
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:650:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at Promise (node_modules/prom-client/lib/cluster.js:74:58)
    at new Promise (<anonymous>)
    at AggregatorRegistry.clusterMetrics (node_modules/prom-client/lib/cluster.js:40:10)
    at metricApp.get (server/server.js:201:26)
    at Layer.handle [as handle_request] ...

**Comment by zbjornson** [comment]
This is fixed by #244. @siimon @SimenB do you have a minute to review that sometime please?

**Comment by zbjornson** [comment]
This was fixed in #244 and released in 11.3.0 🎉
