### ISSUE TITLE
Guage metric reports Invalid Date format when supplying timestamp

### ISSUE THREAD

**Issue by hackmad** [siimon/prom-client#266]
I'm trying to configure a custom metric to report the intervals between websocket heartbeat messages.

```
const client = require('prom-client');

const interval = 5000;

const collectDefaultMetrics = client.collectDefaultMetrics;

const Registry = client.Registry;
const registry = new Registry();

collectDefaultMetrics({
    timeout: interval, 
    register: registry
});

const socketHeartbeat = new client.Gauge({
    name: 'socket_heartbeat',
    help: 'socket_hearbeat',
    registers: [registry]
});

setInterval(() => {
  const delta = engine.heartBeatDeltaSeconds;
  const timestamp = engine.heartBeatTimestamp;
  socketHeartbeat.set(delta, timestamp);
}, 5000);

```

However, it throws an exception:

```
/srv/root/node_modules/prom-client/lib/gauge.js:231
throw new TypeError(
^
2019-05-21T19:45:21.578629700Z 
TypeError: Timestamp is not a valid date or number: 1558467916724
    at /srv/root/node_modules/prom-client/lib/gauge.js:231:10
    at Gauge.set (/srv/root/node_modules/prom-client/lib/gauge.js:89:31)
    at Timeout.setInterval [as _onTimeout] (/srv/root/src/controller/index.js:13:30)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

The value being passed for the timestamp is a valid number. I have tried also doing `new Date(timestamp)` with similar results:

```
> new Date(1558467916724)
2019-05-21T19:45:16.724Z
```

The code works fine if I exclude the timestamp and just do:
```
prometheus.socketHeartbeat.set(delta);
```
or
```
prometheus.socketHeartbeat.set(delta, new Date());
```

Is there something I'm missing?

**Comment by zbjornson** [comment]
Could you try adding something like `console.log(timestamp, typeof timestamp)` below your `const timestamp = engine.heartBeatTimestamp;` line to rule out that it might be a string instead of a number, maybe? Or `socketHeartbeat.set(delta, new Date(timestamp))`?

**Comment by hackmad** [comment]
Realized that the websocket message handler was passing it as string rather than a number.
