### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by mdathrika** [siimon/prom-client#270]
**Version: prom-client 11.5.0**

**TypeError: Cannot read property 'constructor' of null**
  at aggregateByObjectName (/node_modules/prom-client/lib/metrics/helpers/processMetricsHelpers.js:7:37)
  at config.timestamps (/node_modules/prom-client/lib/metrics/processHandles.js:34:26)
  at initialisedMetrics.forEach.metric (/node_modules/prom-client/lib/defaultMetrics.js:70:47)
  at Array.forEach (<anonymous>:null:null)
  at Timeout.updateAllMetrics [as _onTimeout] (/node_modules/prom-client/lib/defaultMetrics.js:70:22)
  at ontimeout (timers.js:498:11)
  at Timer.unrefdHandle (timers.js:611:5)

**Comment by SimenB** [comment]
Could you post a reproduction as well?

**Comment by zbjornson** [comment]
@yvasiyarov this appears to be a regression introduced in #260. Do you have a moment to look at it please?

**Comment by yvasiyarov** [comment]
yes, I will check it in few hours

**Comment by yvasiyarov** [comment]
@mdathrika can you please check if #271 fix this issue ?
fix in the master branch of https://github.com/yvasiyarov/prom-client

**Comment by SimenB** [comment]
Fix out in 11.5.1. @mdathrika a reproduction so we can add a test would be great!
