### ISSUE TITLE
gauge float number

### ISSUE THREAD

**Issue by omersiar** [siimon/prom-client#305]
It seems Prometheus gauge can accept floating point numbers in other implementations. Please see here https://github.com/prometheus/client_python#gauge

But currently prom-client throws an error like below:

```
/root/NodeConnector/node_modules/prom-client/lib/gauge.js:228
                        throw new TypeError(`Value is not a valid number: ${util.format(value)}`);
                        ^

TypeError: Value is not a valid number: 47.81
    at /root/NodeConnector/node_modules/prom-client/lib/gauge.js:228:10
    at Gauge.set (/root/NodeConnector/node_modules/prom-client/lib/gauge.js:91:32)

```

**Comment by omersiar** [comment]
Silly me. Silly, silly, me.
