### ISSUE TITLE
Gauge `collect` function not working

### ISSUE THREAD

**Issue by rhlsthrm** [siimon/prom-client#383]
I'm trying to use the async `collect` function to asynchronously take a measurement.

In Typescript, the type is giving an error:

```
Argument of type '{ name: string; help: string; collect(): Promise<void>; }' is not assignable to parameter of type 'GaugeConfiguration<string>'.
  Object literal may only specify known properties, and 'collect' does not exist in type 'GaugeConfiguration<string>'.
```

And if I ignore the error, it seems that the function is not getting called at all.

**Comment by zbjornson** [comment]
The `async collect()` function is not in a released version yet. If you want to use it, you'll have to install from GitHub: `yarn add siimon/prom-client#4e6aacd`.

**Comment by zbjornson** [comment]
PS: there's a regression in the commit I proposed installing above, which is fixed in #384.

**Comment by rhlsthrm** [comment]
Any idea when it will be released? Also when the PR will be merged? I'm using this in production. I'm currently working around it by manually updating the gauge metric in a setInterval.

**Comment by zbjornson** [comment]
Sorry, I just fixed up #384, and as soon as that's in, I think we can make a release.

**Comment by ricardograca** [comment]
Any news when this release will happen?

**Comment by yorch** [comment]
Also looking forward for a new release so I can use collect in couple of the metrics.
Thanks for the great work!

**Comment by RobertHalwass** [comment]
When I use siimon/prom-client#4e6aacd I always get this Error:
2020-09-14T16:39:21.978468+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise
2020-09-14T16:39:21.978469+00:00 app[web.1]: at ServerResponse.end (_http_outgoing.js:769:13)
2020-09-14T16:39:21.978469+00:00 app[web.1]: at ExpressMiddleware.middleware (/app/node_modules/prometheus-api-metrics/src/express-middleware.js:99:24)
2020-09-14T16:39:21.978470+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-09-14T16:39:21.978470+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2020-09-14T16:39:21.978470+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
2020-09-14T16:39:21.978471+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2020-09-14T16:39:21.978471+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2020-09-14T16:39:21.978471+00:00 app[web.1]: at authMiddleware (/app/node_modules/express-basic-auth/index.js:64:16)
2020-09-14T16:39:21.978472+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-09-14T16:39:21.978472+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2020-09-14T16:39:21.978472+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
2020-09-14T16:39:21.978472+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2020-09-14T16:39:21.978473+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2020-09-14T16:39:21.978473+00:00 app[web.1]: at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
2020-09-14T16:39:21.978473+00:00 app[web.1]: at SendStream.emit (events.js:314:20)
2020-09-14T16:39:21.978473+00:00 app[web.1]: at SendStream.error (/app/node_modules/send/index.js:270:17)

With the current version (12.0.0) the collect function nether seems to get called. Hope there is release soon.

**Comment by rhlsthrm** [comment]
Any updates on this issue now that the related issues are fixed?

**Comment by valtlfelipe** [comment]
Any update on this ?

**Comment by Zeebrommer** [comment]
I ran into this issue as well. It is quite confusing that the master README tells you explicitly:

> you should provide a collect() function, which will be invoked when Prometheus scrapes your metrics endpoint. collect() can either be synchronous or return a promise. See Gauge below for an example. (Note that you should not update metric values in a setInterval callback; do so in this collect function instead.) 

But then the collect function is not working. I'd make PR for the README but I'm not familiar enough with the project to know why you should not use `setInterval`. Is there anything we can do to get to a solution?

**Comment by maxpain** [comment]
Any update?

**Comment by zbjornson** [comment]
Sorry for the delay folks. V13 is out as of a few weeks ago with support for the `collect()` function.

If you use pushgateway, you'll have to install from github (`yarn add siimon/prom-client#83f7867`) until v13.0.1 is released.
