### ISSUE TITLE
pushgateway with promised metrics()

### ISSUE THREAD

**Issue by PierrickP** [siimon/prom-client#416]
According to the new 13.0.0 version `registry.metrics()` return a promise.
But the code was not updated everywhere.
On pushgateway side, https://github.com/siimon/prom-client/blob/master/lib/pushgateway.js#L78

When i push metrics to pushgateway, i got this kind of error
```
    TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise
        at write_ (_http_outgoing.js:696:11)
        at ClientRequest.write (_http_outgoing.js:661:15)
        at Pushgateway.useGateway (/home/pierrickp/works/fluctuo/data-flow/node_modules/prom-client/lib/pushgateway.js:78:7)
        at Pushgateway.pushAdd (/home/pierrickp/works/fluctuo/data-flow/node_modules/prom-client/lib/pushgateway.js:23:14)
        at /home/pierrickp/works/fluctuo/data-flow/jobs/metrics.js:36:15
        at new Promise (<anonymous>)
        at pushMetrics (/home/pierrickp/works/fluctuo/data-flow/jobs/metrics.js:28:10)
        at /home/pierrickp/works/fluctuo/data-flow/jobs/updateZones.js:162:14
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Instant ugly fix

`req.write(await this.registry.metrics());`
Don't forget the `async` keyword on the function.

## A better update

Convert Pushgateway methods (pushAdd / push / pushAdd / delete) to promise form with correct error/rejection handleing

**Comment by SleepWalker** [comment]
This issue was resolved in https://github.com/siimon/prom-client/pull/419 and already released in v13.1.0
