### ISSUE TITLE
Error: A metric with the name process_cpu_user_seconds_total has already been registered.

### ISSUE THREAD

**Issue by uralsemih** [siimon/prom-client#439]
I've a Node.js application where I am using `prom-client ` with v13.1.0 and node14. I cant figure out the below error.

How can I fix this or what should be the root cause of this?

```
/node_modules/prom-client/lib/registry.js:80
                        throw new Error(
                        ^

Error: A metric with the name process_cpu_user_seconds_total has already been registered.
    at Registry.registerMetric (/Users/semural/src/oneapi/documentation-platform-backend/node_modules/prom-client/lib/registry.js:80:10)
    at new Metric (/Users/semural/src/oneapi/documentation-platform-backend/node_modules/prom-client/lib/metric.js:48:13)
    at new Counter (/Users/semural/src/oneapi/documentation-platform-backend/node_modules/prom-client/lib/counter.js:12:1)
    at module.exports (/Users/semural/src/oneapi/documentation-platform-backend/node_modules/prom-client/lib/metrics/processCpuTotal.js:16:30)
    at collectDefaultMetrics (/Users/semural/src/oneapi/documentation-platform-backend/node_modules/prom-client/lib/defaultMetrics.js:43:3)
    at Object.<anonymous> (/Users/semural/src/oneapi/documentation-platform-backend/routes/promRouting.js:7:1)
```

controller.js
```
const prom = require('prom-client');
const collectDefaultMetrics = prom.collectDefaultMetrics;

collectDefaultMetrics({ timeout: 10000 });

exports.collectMetrics = (req, res) => {
    prom.register.clear()
    res.set('Content-Type', prom.register.contentType);
    res.end(await(prom.register.metrics()));
}
```
route.js
```
const express = require('express');
const promController = require("../controllers/promController");
const router = express.Router();


const { collectDefaultMetrics, register } = require('prom-client');
collectDefaultMetrics({ timeout: 10000 });

router.get('/metrics', promController.collectMetrics);

module.exports = router;
```
app.js

```
const app2 = express();

app2.use(promRoutes);


if (global.config.prometheus_enabled === true) {
  app2.listen(9183, '0.0.0.0', () => {
    console.log("Prometheus server starting on 9183")
  });
}

```

**Comment by michaelrommel** [comment]
You are adding the DefaultMetrics twice to the default Registry. Once in `promRoutes` and once in `promController`

**Comment by zbjornson** [comment]
@michaelrommel is correct, you should only call `collectDefaultMetrics()` once.
