### ISSUE TITLE
prom-client tests are failing

### ISSUE THREAD

**Issue by phracek** [siimon/prom-client#483]
prom-client test suite is failing:

```bash
> prom-client@14.0.1 test /opt/app-root/src
> npm run lint && npm run compile-typescript && npm run test-unit


> prom-client@14.0.1 lint /opt/app-root/src
> eslint .


> prom-client@14.0.1 compile-typescript /opt/app-root/src
> tsc --project .


> prom-client@14.0.1 test-unit /opt/app-root/src
> jest

PASS test/summaryTest.js
FAIL test/registerTest.js
  ● register › should have the same contentType as the module

    Cannot find module '../' from 'test/registerTest.js'

      611 | 
      612 | it('should have the same contentType as the module', () => {
    > 613 | const moduleWideContentType = require('../').contentType;
          |                               ^
      614 | expect(register.contentType).toEqual(moduleWideContentType);
      615 | });
      616 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (test/registerTest.js:613:33)

PASS test/histogramTest.js
PASS test/gaugeTest.js
PASS test/counterTest.js
PASS test/clusterTest.js
PASS test/pushgatewayTest.js
PASS test/pushgatewayWithPathTest.js
PASS test/aggregatorsTest.js
PASS test/defaultMetricsTest.js
PASS test/metrics/heapSpacesSizeAndUsedTest.js
PASS test/metrics/eventLoopLagTest.js
PASS test/timeWindowQuantilesTest.js
PASS test/bucketGeneratorsTest.js
PASS test/metrics/maxFileDescriptorsTest.js
PASS test/metrics/versionTest.js
PASS test/metrics/heapSizeAndUsedTest.js
PASS test/metrics/gcTest.js
PASS test/metrics/processRequestsTest.js
PASS test/metrics/processHandlesTest.js
PASS test/metrics/processStartTimeTest.js
PASS test/metrics/processOpenFileDescriptorsTest.js
PASS test/validationTest.js

Summary of all failing tests
FAIL test/registerTest.js
  ● register › should have the same contentType as the module

    Cannot find module '../' from 'test/registerTest.js'

      611 | 
      612 | it('should have the same contentType as the module', () => {
    > 613 | const moduleWideContentType = require('../').contentType;
          |                               ^
      614 | expect(register.contentType).toEqual(moduleWideContentType);
      615 | });
      616 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (test/registerTest.js:613:33)


Test Suites: 1 failed, 22 passed, 23 total
```

**Comment by zbjornson** [comment]
I can't reproduce the failure locally or in CI (e.g. https://github.com/siimon/prom-client/runs/4680786861?check_suite_focus=true). The first line of your paste (`> prom-client@14.0.1 test /opt/app-root/src`) looks odd; for me it's this:

```
prom-client> yarn test
yarn run v1.22.17
$ npm run lint && npm run compile-typescript && npm run test-unit

> prom-client@14.0.1 lint C:\Users\zachb\git\prom-client
> eslint .


> prom-client@14.0.1 compile-typescript C:\Users\zachb\git\prom-client
> tsc --project .


> prom-client@14.0.1 test-unit C:\Users\zachb\git\prom-client
> jest
```

with, notably, `test-unit` and `prom-client` in the last line. How did you retrieve prom-client (to get `/opt/app-root/src`) and how are you running the tests (to get a `test` task)?
